###
GET http://localhost:1337

###
POST http://localhost:1337
Content-Type: application/json

{
    "name": "Komron",
    "location" : "Midwood"
}

###
POST http://localhost:1337/users/register
Content-Type: application/json

{
    "name": "Davron Usmonov",
    "email": "dave4@gmail.com",
    "password": "test1234",
    "password2": "test1234"
}

###
POST http://localhost:1337/users/login
Content-Type: application/json

{
    "email": "dave1@gmail.com",
    "password" : "test123"
}
